### ISSUE TITLE
Collision.SphereSphere in test_Collision fails on Windows

### ISSUE THREAD

**Issue by traversaro** [conda-forge/dartsim-feedstock#63]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

See https://github.com/conda-forge/dartsim-feedstock/pull/60#issuecomment-2007537510 .

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by jslee02** [comment]
I haven't examined it in detail, but the test failure might be due to a rounding error. Initially, the test verified if two spheres touched at a distance equal to their radii's sum. I've adjusted the test criteria to allow for an overlap within a tolerance of 1e-12, resulting in the test passing. Here are the [commit](https://github.com/dartsim/dart/commit/60bc493095cccd8ef12f5a2f9d0af0268786fe6e) in master (for 6.14) and its [build log](https://github.com/dartsim/dart/actions/runs/8360994383/job/22887984687).

**Comment by traversaro** [comment]
Thanks, that is great. At this point probably we can just wait for the 6.14.0 release and then remove the exclusion of test_Collision  there.

**Comment by jslee02** [comment]
Sounds good to me!
